/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettopokemon;

/**
 *
 * @author montedori.riccardo
 */
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class InterfacciaSceltaPokemon extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaSceltaPokemon.class.getName());

    /**
     * Creates new form InterfacciaSceltaPokemon
     */
    private Image imgOriginale = new ImageIcon("immagine_scelta_pokemon.png").getImage();
    private Image imgFroakie = new ImageIcon("immagine_froakie.png").getImage();
    private Image imgRowlet = new ImageIcon("immagine_rowlet.png").getImage();
    private Image imgChimchar = new ImageIcon("immagine_chimchar.png").getImage();

    public InterfacciaSceltaPokemon() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);


        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int w = getContentPane().getWidth();
                int h = getContentPane().getHeight();

                if (w > 0 && h > 0) {
                    jLabel1.setBounds(0, 0, w, h);
                    jLabel1.setIcon(new ImageIcon(imgOriginale.getScaledInstance(w, h, Image.SCALE_SMOOTH)));

                    int btnW = w / 12;
                    int btnH = h / 6;


                    jButton2.setBounds((int) (w * 0.335), (int) (h * 0.30), btnW, btnH);
                    aggiornaIconaBottone(jButton2, imgChimchar);


                    jButton3.setBounds((int) (w * 0.46), (int) (h * 0.30), btnW, btnH);
                    aggiornaIconaBottone(jButton3, imgRowlet);


                    jButton4.setBounds((int) (w * 0.585), (int) (h * 0.30), btnW, btnH);
                    aggiornaIconaBottone(jButton4, imgFroakie);

                    getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);
                }
            }
        });
        jButton2.addActionListener(e -> apriNuovaInterfaccia("Chimchar"));
        jButton3.addActionListener(e -> apriNuovaInterfaccia("Rowlet"));
        jButton4.addActionListener(e -> apriNuovaInterfaccia("Froakie"));

    }

    private void aggiornaIconaBottone(javax.swing.JButton btn, Image img) {
        if (btn.getWidth() > 0 && btn.getHeight() > 0) {
            Image scaled = img.getScaledInstance(btn.getWidth(), btn.getHeight(), Image.SCALE_SMOOTH);
            btn.setIcon(new ImageIcon(scaled));
        }
    }

    private void apriNuovaInterfaccia(String pokemonScelto) {
        InterfacciaSvolgimentoGioco nuovaSchermata = new InterfacciaSvolgimentoGioco();
        nuovaSchermata.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 190, 75, 23);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(160, 190, 75, 23);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(260, 190, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaSceltaPokemon().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
