/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettopokemon;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author montedori.riccardo
 */
public class InterfacciaInventario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaInventario.class.getName());

    /**
     * Creates new form InterfacciaInventario
     */
    Inventario i;
    Gestore g;
    private Image imgInventario = new ImageIcon("immagine_inventario.png").getImage();

    public InterfacciaInventario(Gestore g) {
        this.g = g;
        initComponents();
        btnChiudiInventario.setOpaque(false);
        btnChiudiInventario.setContentAreaFilled(false);
        btnChiudiInventario.setBorderPainted(true); 
        btnChiudiInventario.setFocusPainted(false);

        btnChiudiInventario.setForeground(new java.awt.Color(153, 255, 51));

        btnChiudiInventario.setFont(new java.awt.Font("SimSun-ExtB", 1, 14));
        
        getContentPane().setLayout(null);

        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int w = getContentPane().getWidth();
                int h = getContentPane().getHeight();

                if (w > 0 && h > 0) {
                    
                    java.net.URL imgURL = getClass().getResource("immagine_inventario.png");
                    ImageIcon icona = (imgURL != null) ? new ImageIcon(imgURL) : new ImageIcon("immagine_inventario.png");

                    if (icona.getImage() != null) {
                        Image imgRiscalata = icona.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
                        jLabel6.setIcon(new ImageIcon(imgRiscalata));
                        jLabel6.setText("");
                        jLabel6.setBounds(0, 0, w, h);
                    }

                   
                    int centroX = (w / 2) - 100; 
                    int colonnaNumeriX = centroX + 160; 

                    
                    jLabel5.setBounds((w - 150) / 2, 30, 150, 32);

                    
                    jLabel1.setBounds(centroX, 100, 150, 14); 
                    jLabel12.setBounds(colonnaNumeriX, 100, 50, 14);

                    jLabel2.setBounds(centroX, 130, 150, 14); 
                    jLabel11.setBounds(colonnaNumeriX, 130, 50, 14);

                    jLabel3.setBounds(centroX, 160, 150, 14); 
                    jLabel9.setBounds(colonnaNumeriX, 160, 50, 14);

                    jLabel4.setBounds(centroX, 190, 220, 20);  
                    jLabel10.setBounds(colonnaNumeriX, 190, 50, 20);

                    
                    int btnW = 200; 
                    int btnH = 30;
                    int btnX = (w - btnW) / 2;
                    int btnY = h - 70; 
                    btnChiudiInventario.setBounds((w - btnW) / 2, h - 70, btnW, btnH);
                    getContentPane().setComponentZOrder(jLabel6, getContentPane().getComponentCount() - 1);
                }
            }
        });

        g.getInventario();
        aggiornaDati();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public void aggiornaDati() {
        jLabel12.setText("" + g.getInventario().getN_pozioni());
        jLabel11.setText("" + g.getInventario().getN_bacche());
        jLabel9.setText("" + g.getInventario().getN_acqua());
        jLabel10.setText("" + g.getInventario().getN_revitalizzanti());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnChiudiInventario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 51));
        jLabel1.setText("Numero Pozioni:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 120, 17);

        jLabel2.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setText("Numero Bacche:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 110, 130, 17);

        jLabel3.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 51));
        jLabel3.setText("Numero Acquee:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 140, 120, 17);

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 51));
        jLabel4.setText("Numero Pepite:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 180, 17);

        btnChiudiInventario.setText("Chiudi Inventario");
        btnChiudiInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnChiudiInventario);
        btnChiudiInventario.setBounds(250, 250, 130, 23);

        jLabel9.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 51));
        jLabel9.setText("0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 140, 100, 17);

        jLabel10.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 51));
        jLabel10.setText("0");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 170, 130, 17);

        jLabel11.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 51));
        jLabel11.setText("0");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 110, 100, 17);

        jLabel12.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 51));
        jLabel12.setText("0");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(140, 80, 100, 17);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 51));
        jLabel5.setText("INVENTARIO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 20, 150, 32);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 240, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiInventarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnChiudiInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfacciaInventario(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudiInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
